### PR TITLE
Minor Tweaks

### PR DESCRIPTION
**Pull request by A-Everyman**
Final Phrasing and Handle updates w/ Icons

### CODE REVIEW

**Comment by byronic** [comment]
I like this except for the icons. We need to either pull icons from a Blizzard-provided fansite bundle or make our own -- hotlinking to deviantart or other image sources is not appropriate for our use case. If you want, you can temporarily change the `src=` tags to have `#` for the link.

After that will be happy to merge this

**Comment by A-Everyman** [comment]
I agree with all points. I'll look for fansite kits in a bit.
- Joseph Vaughan

**Comment by A-Everyman** [comment]
Not really sure how to do this tho. I have taken some png files from fan
kits or other free to use sources. I did double check that with each. Not
sure how you want to get them on there if we are not hotlinking to our own
source. Attaching them so you can put them up however you want.
- Joseph Vaughan

**Comment by A-Everyman** [comment]
diablo_iii_ros_icon
doom-4-icon
download fv4
icon-hearthstone
starcraft-2
wow-logo

**Pull request merged**
